#!/bin/bash

array=(https://google.com https://facebook.com https://twitter.com https://curl.se)

result_file="website_status.log"

> $result_file

index=0

while [ $index -lt ${#array[@]} ]
do
	status=$(curl -o /dev/null -s -w "%{http_code}" ${array[$index]})

	if [[ ( $status -ge 200 ) && ( $status -lt 300 ) ]]
	then
		echo "${array[$index]} is UP with a $status status" >> $result_file
	else
		echo "${array[$index]} is DOWN with a $status status" >> $result_file
	fi
	(( index++ ))
done

echo "Now you can check the file with results"
